from globals import *
from enum import Enum
import random
from numpy.random import choice

class PokemonType(Enum):
     NA= 0,
     STEEL = 1,
     ELECTRIC = 2,
     ICE = 3,
     NORMAL = 4,
     FIRE = 5,
     PSYCHIC = 6,
     FLYING = 7,
     POISON = 8,
     DRAGON = 9,
     WATER = 10,
     GHOST = 11,
     FIGHTING = 12,
     ROCK = 13,
     FAIRY = 14,
     GRASS = 15,
     BUG = 16,
     GROUND = 17,
     DARK = 18

pokemon_type_interaction = {
    PokemonType.BUG: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 2.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 0.5,
            PokemonType.FIGHTING: 0.5,
            PokemonType.FIRE: 0.5,
            PokemonType.FLYING: 0.5,
            PokemonType.GHOST: 0.5,
            PokemonType.GRASS: 2.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 0.5,
            PokemonType.PSYCHIC: 2.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 1.0
        },
        PokemonType.DARK: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 0.5,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 0.5,
            PokemonType.FIGHTING: 0.5,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 2.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 2.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 1.0,
            PokemonType.WATER: 1.0
        },
        PokemonType.DRAGON: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 2.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 0.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 1.0
        },
        PokemonType.ELECTRIC: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 0.5,
            PokemonType.ELECTRIC: 0.5,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 2.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 0.5,
            PokemonType.GROUND: 0.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 1.0,
            PokemonType.WATER: 2.0
        },
        PokemonType.FAIRY: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 2.0,
            PokemonType.DRAGON: 2.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 2.0,
            PokemonType.FIRE: 0.5,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 0.5,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 1.0
        },
        PokemonType.FIGHTING: {
            PokemonType.BUG: 0.5,
            PokemonType.DARK: 2.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 0.5,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 0.5,
            PokemonType.GHOST: 0.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 2.0,
            PokemonType.NORMAL: 2.0,
            PokemonType.POISON: 0.5,
            PokemonType.PSYCHIC: 0.5,
            PokemonType.ROCK: 2.0,
            PokemonType.STEEL: 2.0,
            PokemonType.WATER: 1.0
        },
        PokemonType.FIRE: {
            PokemonType.BUG: 2.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 0.5,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 0.5,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 2.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 2.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 0.5,
            PokemonType.STEEL: 2.0,
            PokemonType.WATER: 0.5
        },
        PokemonType.FLYING: {
            PokemonType.BUG: 2.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 0.5,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 2.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 2.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 0.5,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 1.0
        },
        PokemonType.GHOST: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 0.5,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 2.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 0.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 2.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 1.0,
            PokemonType.WATER: 1.0
        },
        PokemonType.GRASS: {
            PokemonType.BUG: 0.5,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 0.5,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 0.5,
            PokemonType.FLYING: 0.5,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 0.5,
            PokemonType.GROUND: 2.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 0.5,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 2.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 2.0
        },
        PokemonType.GROUND: {
            PokemonType.BUG: 0.5,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 2.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 2.0,
            PokemonType.FLYING: 0.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 0.5,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 2.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 2.0,
            PokemonType.STEEL: 2.0,
            PokemonType.WATER: 1.0
        },
        PokemonType.ICE: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 2.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 0.5,
            PokemonType.FLYING: 2.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 2.0,
            PokemonType.GROUND: 2.0,
            PokemonType.ICE: 0.5,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 0.5
        },
        PokemonType.NORMAL: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 0.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 0.5,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 1.0
        },
        PokemonType.POISON: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 2.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 0.5,
            PokemonType.GRASS: 2.0,
            PokemonType.GROUND: 0.5,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 0.5,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 0.5,
            PokemonType.STEEL: 0.0,
            PokemonType.WATER: 1.0
        },
        PokemonType.PSYCHIC: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 0.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 2.0,
            PokemonType.FIRE: 1.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 2.0,
            PokemonType.PSYCHIC: 0.5,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 1.0
        },
        PokemonType.ROCK: {
            PokemonType.BUG: 2.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 0.5,
            PokemonType.FIRE: 2.0,
            PokemonType.FLYING: 2.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 0.5,
            PokemonType.ICE: 2.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 1.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 1.0
        },
        PokemonType.STEEL: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 1.0,
            PokemonType.ELECTRIC: 0.5,
            PokemonType.FAIRY: 2.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 0.5,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 1.0,
            PokemonType.GROUND: 1.0,
            PokemonType.ICE: 2.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 2.0,
            PokemonType.STEEL: 0.5,
            PokemonType.WATER: 0.5
        },
        PokemonType.WATER: {
            PokemonType.BUG: 1.0,
            PokemonType.DARK: 1.0,
            PokemonType.DRAGON: 0.5,
            PokemonType.ELECTRIC: 1.0,
            PokemonType.FAIRY: 1.0,
            PokemonType.FIGHTING: 1.0,
            PokemonType.FIRE: 2.0,
            PokemonType.FLYING: 1.0,
            PokemonType.GHOST: 1.0,
            PokemonType.GRASS: 0.5,
            PokemonType.GROUND: 2.0,
            PokemonType.ICE: 1.0,
            PokemonType.NORMAL: 1.0,
            PokemonType.POISON: 1.0,
            PokemonType.PSYCHIC: 1.0,
            PokemonType.ROCK: 2.0,
            PokemonType.STEEL: 1.0,
            PokemonType.WATER: 0.5
        }
}

class PokemonData(object):
     def __init__(self, poke_id, name, type1, type2):
          self.poke_id = poke_id
          self.name = name
          self.poke_types = (type1, type2)

     def __hash__(self):
          return self.poke_id

     def __eq__(self,other):
          return self.poke_id == other.poke_id

     __str__= lambda self: str(self.__dict__)

     __repr__=__str__

class PokemonEgg(object):
     def __init__(self, pokemon, steps):
          self.pokemon = pokemon
          self.steps = steps


def resolve_damage(pokemon_a, pokemon_d):
     global pokemon_type_interaction
     if pokemon_a.poke_types[1] == PokemonType.NA: 
          atacking_type= pokemon_a.poke_types[0]
     else:
          atacking_type= random.choice(pokemon_a)
     atack = pokemon_type_interaction[atacking_type]
     for t in pokemon_d.poke_types:
          damage=1
          type_damage = atack.get(t)
          if type_damage is not None:
               damage *= type_damage
     return type_damage


common_pokemon =[
    [0.0151, PokemonData(001, 'bulbasaur', PokemonType.GRASS, PokemonType.POISON)],
    [0.015, PokemonData(002, 'ivysaur', PokemonType.GRASS, PokemonType.POISON)],
    [0.0149, PokemonData(003, 'venusaur', PokemonType.GRASS, PokemonType.POISON)],
    [0.0148, PokemonData(004, 'charmander', PokemonType.FIRE, PokemonType.NA)],
    [0.0147, PokemonData(005, 'charmeleon', PokemonType.FIRE, PokemonType.NA)],
    [0.0146, PokemonData(006, 'charizard', PokemonType.FIRE, PokemonType.FLYING)],
    [0.0145, PokemonData(007, 'squirtle', PokemonType.WATER, PokemonType.NA)],
    [0.0144, PokemonData(8, 'wartortle', PokemonType.WATER, PokemonType.NA)],
    [0.0143, PokemonData(9, 'blastoise', PokemonType.WATER, PokemonType.NA)],
    [0.142, PokemonData(010, 'caterpie', PokemonType.BUG, PokemonType.NA)],
    [0.141, PokemonData(011, 'metapod', PokemonType.BUG, PokemonType.NA)],
    [0.14, PokemonData(012, 'butterfree', PokemonType.BUG, PokemonType.FLYING)],
    [0.139, PokemonData(013, 'weedle', PokemonType.BUG, PokemonType.POISON)],
    [0.138, PokemonData(014, 'kakuna', PokemonType.BUG, PokemonType.POISON)],
    [0.137, PokemonData(015, 'beedrill', PokemonType.BUG, PokemonType.POISON)],
    [0.136, PokemonData(016, 'pidgey', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.135, PokemonData(017, 'pidgeotto', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.134, PokemonData(18, 'pidgeot', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.133, PokemonData(19, 'rattata', PokemonType.NORMAL, PokemonType.NA)],
    [0.132, PokemonData(020, 'raticate', PokemonType.NORMAL, PokemonType.NA)],
    [0.131, PokemonData(021, 'spearow', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.13, PokemonData(022, 'fearow', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.129, PokemonData(023, 'ekans', PokemonType.POISON, PokemonType.NA)],
    [0.128, PokemonData(024, 'arbok', PokemonType.POISON, PokemonType.NA)],
    [0.127, PokemonData(025, 'pikachu', PokemonType.ELECTRIC, PokemonType.NA)],
    [0.126, PokemonData(026, 'raichu', PokemonType.ELECTRIC, PokemonType.NA)],
    [0.125, PokemonData(027, 'sandshrew', PokemonType.GROUND, PokemonType.NA)],
    [0.124, PokemonData(28, 'sandslash', PokemonType.GROUND, PokemonType.NA)],
    [0.123, PokemonData(29, 'nidoran-m', PokemonType.POISON, PokemonType.NA)],
    [0.122, PokemonData(030, 'nidorina', PokemonType.POISON, PokemonType.NA)],
    [0.121, PokemonData(031, 'nidoqueen', PokemonType.POISON, PokemonType.GROUND)],
    [0.12, PokemonData(032, 'nidoran-f', PokemonType.POISON, PokemonType.NA)],
    [0.119, PokemonData(033, 'nidorino', PokemonType.POISON, PokemonType.NA)],
    [0.118, PokemonData(034, 'nidoking', PokemonType.POISON, PokemonType.GROUND)],
    [0.117, PokemonData(035, 'clefairy', PokemonType.FAIRY, PokemonType.NA)],
    [0.116, PokemonData(036, 'clefable', PokemonType.FAIRY, PokemonType.NA)],
    [0.115, PokemonData(037, 'vulpix', PokemonType.FIRE, PokemonType.NA)],
    [0.114, PokemonData(38, 'ninetales', PokemonType.FIRE, PokemonType.NA)],
    [0.113, PokemonData(39, 'jigglypuff', PokemonType.NORMAL, PokemonType.FAIRY)],
    [0.112, PokemonData(040, 'wigglytuff', PokemonType.NORMAL, PokemonType.FAIRY)],
    [0.111, PokemonData(041, 'zubat', PokemonType.POISON, PokemonType.FLYING)],
    [0.11, PokemonData(042, 'golbat', PokemonType.POISON, PokemonType.FLYING)],
    [0.109, PokemonData(043, 'oddish', PokemonType.GRASS, PokemonType.POISON)],
    [0.108, PokemonData(044, 'gloom', PokemonType.GRASS, PokemonType.POISON)],
    [0.107, PokemonData(045, 'vileplume', PokemonType.GRASS, PokemonType.POISON)],
    [0.106, PokemonData(046, 'paras', PokemonType.BUG, PokemonType.GRASS)],
    [0.105, PokemonData(047, 'parasect', PokemonType.BUG, PokemonType.GRASS)],
    [0.104, PokemonData(48, 'venonat', PokemonType.BUG, PokemonType.POISON)],
    [0.103, PokemonData(49, 'venomoth', PokemonType.BUG, PokemonType.POISON)],
    [0.102, PokemonData(050, 'diglett', PokemonType.GROUND, PokemonType.NA)],
    [0.101, PokemonData(051, 'dugtrio', PokemonType.GROUND, PokemonType.NA)],
    [0.1, PokemonData(052, 'meowth', PokemonType.NORMAL, PokemonType.NA)],
    [0.099, PokemonData(053, 'persian', PokemonType.NORMAL, PokemonType.NA)],
    [0.098, PokemonData(054, 'psyduck', PokemonType.WATER, PokemonType.NA)],
    [0.097, PokemonData(055, 'golduck', PokemonType.WATER, PokemonType.NA)],
    [0.096, PokemonData(056, 'mankey', PokemonType.FIGHTING, PokemonType.NA)],
    [0.095, PokemonData(057, 'primeape', PokemonType.FIGHTING, PokemonType.NA)],
    [0.094, PokemonData(58, 'growlithe', PokemonType.FIRE, PokemonType.NA)],
    [0.093, PokemonData(59, 'arcanine', PokemonType.FIRE, PokemonType.NA)],
    [0.092, PokemonData(060, 'poliwag', PokemonType.WATER, PokemonType.NA)],
    [0.091, PokemonData(061, 'poliwhirl', PokemonType.WATER, PokemonType.NA)],
    [0.09, PokemonData(062, 'poliwrath', PokemonType.WATER, PokemonType.FIGHTING)],
    [0.089, PokemonData(063, 'abra', PokemonType.PSYCHIC, PokemonType.NA)],
    [0.088, PokemonData(064, 'kadabra', PokemonType.PSYCHIC, PokemonType.NA)],
    [0.087, PokemonData(065, 'alakazam', PokemonType.PSYCHIC, PokemonType.NA)],
    [0.086, PokemonData(066, 'machop', PokemonType.FIGHTING, PokemonType.NA)],
    [0.085, PokemonData(067, 'machoke', PokemonType.FIGHTING, PokemonType.NA)],
    [0.084, PokemonData(68, 'machamp', PokemonType.FIGHTING, PokemonType.NA)],
    [0.083, PokemonData(69, 'bellsprout', PokemonType.GRASS, PokemonType.POISON)],
    [0.082, PokemonData(070, 'weepinbell', PokemonType.GRASS, PokemonType.POISON)],
    [0.081, PokemonData(071, 'victreebel', PokemonType.GRASS, PokemonType.POISON)],
    [0.08, PokemonData(072, 'tentacool', PokemonType.WATER, PokemonType.POISON)],
    [0.079, PokemonData(073, 'tentacruel', PokemonType.WATER, PokemonType.POISON)],
    [0.078, PokemonData(074, 'geodude', PokemonType.ROCK, PokemonType.GROUND)],
    [0.077, PokemonData(075, 'graveler', PokemonType.ROCK, PokemonType.GROUND)],
    [0.076, PokemonData(076, 'golem', PokemonType.ROCK, PokemonType.GROUND)],
    [0.075, PokemonData(077, 'ponyta', PokemonType.FIRE, PokemonType.NA)],
    [0.074, PokemonData(78, 'rapidash', PokemonType.FIRE, PokemonType.NA)],
    [0.073, PokemonData(79, 'slowpoke', PokemonType.WATER, PokemonType.PSYCHIC)],
    [0.072, PokemonData(80, 'slowbro', PokemonType.WATER, PokemonType.PSYCHIC)],
    [0.071, PokemonData(81, 'magnemite', PokemonType.ELECTRIC, PokemonType.STEEL)],
    [0.07, PokemonData(82, 'magneton', PokemonType.ELECTRIC, PokemonType.STEEL)],
    [0.069, PokemonData(83, 'farfetchd', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.068, PokemonData(84, 'doduo', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.067, PokemonData(85, 'dodrio', PokemonType.NORMAL, PokemonType.FLYING)],
    [0.066, PokemonData(86, 'seel', PokemonType.WATER, PokemonType.NA)],
    [0.065, PokemonData(87, 'dewgong', PokemonType.WATER, PokemonType.ICE)],
    [0.064, PokemonData(88, 'grimer', PokemonType.POISON, PokemonType.NA)],
    [0.063, PokemonData(89, 'muk', PokemonType.POISON, PokemonType.NA)],
    [0.062, PokemonData(90, 'shellder', PokemonType.WATER, PokemonType.NA)],
    [0.061, PokemonData(91, 'cloyster', PokemonType.WATER, PokemonType.ICE)],
    [0.06, PokemonData(92, 'gastly', PokemonType.GHOST, PokemonType.POISON)],
    [0.059, PokemonData(93, 'haunter', PokemonType.GHOST, PokemonType.POISON)],
    [0.058, PokemonData(94, 'gengar', PokemonType.GHOST, PokemonType.POISON)],
    [0.057, PokemonData(95, 'onix', PokemonType.ROCK, PokemonType.GROUND)],
    [0.056, PokemonData(96, 'drowzee', PokemonType.PSYCHIC, PokemonType.NA)],
    [0.055, PokemonData(97, 'hypno', PokemonType.PSYCHIC, PokemonType.NA)],
    [0.054, PokemonData(98, 'krabby', PokemonType.WATER, PokemonType.NA)],
    [0.053, PokemonData(99, 'kingler', PokemonType.WATER, PokemonType.NA)],
    [0.052, PokemonData(100, 'voltorb', PokemonType.ELECTRIC, PokemonType.NA)],
    [0.051, PokemonData(101, 'electrode', PokemonType.ELECTRIC, PokemonType.NA)],
    [0.05, PokemonData(102, 'exeggcute', PokemonType.GRASS, PokemonType.PSYCHIC)],
    [0.049, PokemonData(103, 'exeggutor', PokemonType.GRASS, PokemonType.PSYCHIC)],
    [0.048, PokemonData(104, 'cubone', PokemonType.GROUND, PokemonType.NA)],
    [0.047, PokemonData(105, 'marowak', PokemonType.GROUND, PokemonType.NA)],
    [0.046, PokemonData(106, 'hitmonlee', PokemonType.FIGHTING, PokemonType.NA)],
    [0.045, PokemonData(107, 'hitmonchan', PokemonType.FIGHTING, PokemonType.NA)],
    [0.044, PokemonData(108, 'lickitung', PokemonType.NORMAL, PokemonType.NA)],
    [0.043, PokemonData(109, 'koffing', PokemonType.POISON, PokemonType.NA)],
    [0.042, PokemonData(110, 'weezing', PokemonType.POISON, PokemonType.NA)],
    [0.041, PokemonData(111, 'rhyhorn', PokemonType.GROUND, PokemonType.ROCK)],
    [0.04, PokemonData(112, 'rhydon', PokemonType.GROUND, PokemonType.ROCK)],
    [0.039, PokemonData(113, 'chansey', PokemonType.NORMAL, PokemonType.NA)],
    [0.038, PokemonData(114, 'tangela', PokemonType.GRASS, PokemonType.NA)],
    [0.037, PokemonData(115, 'kangaskhan', PokemonType.NORMAL, PokemonType.NA)],
    [0.036, PokemonData(116, 'horsea', PokemonType.WATER, PokemonType.NA)],
    [0.035, PokemonData(117, 'seadra', PokemonType.WATER, PokemonType.NA)],
    [0.034, PokemonData(118, 'goldeen', PokemonType.WATER, PokemonType.NA)],
    [0.033, PokemonData(119, 'seaking', PokemonType.WATER, PokemonType.NA)],
    [0.032, PokemonData(120, 'staryu', PokemonType.WATER, PokemonType.NA)],
    [0.031, PokemonData(121, 'starmie', PokemonType.WATER, PokemonType.PSYCHIC)],
    [0.03, PokemonData(122, 'mr-mime', PokemonType.PSYCHIC, PokemonType.FAIRY)],
    [0.029, PokemonData(123, 'scyther', PokemonType.BUG, PokemonType.FLYING)],
    [0.028, PokemonData(124, 'jynx', PokemonType.ICE, PokemonType.PSYCHIC)],
    [0.027, PokemonData(125, 'electabuzz', PokemonType.ELECTRIC, PokemonType.NA)],
    [0.026, PokemonData(126, 'magmar', PokemonType.FIRE, PokemonType.NA)],
    [0.025, PokemonData(127, 'pinsir', PokemonType.BUG, PokemonType.NA)],
    [0.024, PokemonData(128, 'tauros', PokemonType.NORMAL, PokemonType.NA)],
    [0.023, PokemonData(129, 'magikarp', PokemonType.WATER, PokemonType.NA)],
    [0.022, PokemonData(130, 'gyarados', PokemonType.WATER, PokemonType.FLYING)],
    [0.021, PokemonData(131, 'lapras', PokemonType.WATER, PokemonType.ICE)],
    [0.02, PokemonData(132, 'ditto', PokemonType.NORMAL, PokemonType.NA)],
    [0.019, PokemonData(133, 'eevee', PokemonType.NORMAL, PokemonType.NA)],
    [0.018, PokemonData(134, 'vaporeon', PokemonType.WATER, PokemonType.NA)],
    [0.017, PokemonData(135, 'jolteon', PokemonType.ELECTRIC, PokemonType.NA)],
    [0.016, PokemonData(136, 'flareon', PokemonType.FIRE, PokemonType.NA)],
    [0.015, PokemonData(137, 'porygon', PokemonType.NORMAL, PokemonType.NA)],
    [0.014, PokemonData(138, 'omanyte', PokemonType.ROCK, PokemonType.WATER)],
    [0.013, PokemonData(139, 'omastar', PokemonType.ROCK, PokemonType.WATER)],
    [0.012, PokemonData(140, 'kabuto', PokemonType.ROCK, PokemonType.WATER)],
    [0.011, PokemonData(141, 'kabutops', PokemonType.ROCK, PokemonType.WATER)],
    [0.01, PokemonData(142, 'aerodactyl', PokemonType.ROCK, PokemonType.FLYING)],
    [0.009, PokemonData(143, 'snorlax', PokemonType.NORMAL, PokemonType.NA)],
    [0.005, PokemonData(147, 'dratini', PokemonType.DRAGON, PokemonType.NA)],
    [0.004, PokemonData(148, 'dragonair', PokemonType.DRAGON, PokemonType.NA)],
    [0.003, PokemonData(149, 'dragonite', PokemonType.DRAGON, PokemonType.FLYING)],
]
legendery_pokemon_chance = 0.01
legendery_pokemon = [
    [0.08, PokemonData(144, 'articuno', PokemonType.ICE, PokemonType.FLYING)],
    [0.07, PokemonData(145, 'zapdos', PokemonType.ELECTRIC, PokemonType.FLYING)],
    [0.06, PokemonData(146, 'moltres', PokemonType.FIRE, PokemonType.FLYING)],
    [0.02, PokemonData(150, 'mewtwo', PokemonType.PSYCHIC, PokemonType.NA)],
    [0.001, PokemonData(151, 'mew', PokemonType.PSYCHIC, PokemonType.NA)],
    [0.001, PokemonData(152, 'andy_badger', PokemonType.PSYCHIC, PokemonType.GHOST)],
    [0.001, PokemonData(153, 'misingno', PokemonType.NORMAL, PokemonType.FLYING)]
 ]
common_pokemon_pd, common_pokemon = map(list, zip(*common_pokemon))

def get_random_pokemon():
    global legendery_pokemon
    poke = "misingno"
    legendery_pokemon_pd, _legendery_pokemon = map(list, zip(*legendery_pokemon))
    total_p = sum(legendery_pokemon_pd)
    if total_p > 0 and random.random() < legendery_pokemon_chance:
        #legendary pokemon
        legendery_pokemon_pd = [float(x)/total_p for x in legendery_pokemon_pd]
        poke = choice(
            _legendery_pokemon,
            1,
            p=legendery_pokemon_pd,
            replace=False
        )[0]
    else:
        #normal
        global common_pokemon_pd
        total_p = sum(common_pokemon_pd)
        common_pokemon_pd = [float(x)/total_p for x in common_pokemon_pd]
        poke = choice(
            common_pokemon,
            1,
            p=common_pokemon_pd,
            replace=False
        )[0]
    return poke
